name: Main
on:
  schedule:
    - cron: "5 5 * * TUE"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: true
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1.213.0
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: |
          echo "dates=$(bundle exec backup.rb list)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
        id: dates
      - run: |
          echo "Unknown dates -- ${UNKNOWN_DATES}"
          echo "last date -- ${LAST_DATE}"
          echo "first date -- ${FIRST_DATE}"
        env:
          UNKNOWN_DATES: "${{ steps.dates.outputs.dates }}"
          LAST_DATE: "${{ fromJson(steps.dates.outputs.dates)[-1] }}"
          FIRST_DATE: "${{ fromJson(steps.dates.outputs.dates)[0] }}"
      - run: bundle exec backup.rb download ${BACKUP_PATH}
        env:
          BACKUP_PATH: ${{ fromJson(steps.dates.outputs.dates)[0] }}
      - run: bundle exec backup.rb dump ${BACKUP_PATH}
        env:
          BACKUP_PATH: ${{ fromJson(steps.dates.outputs.dates)[0] }}
      - run: bundle exec backup.rb commit ${BACKUP_PATH}
        env:
          BACKUP_PATH: ${{ fromJson(steps.dates.outputs.dates)[0] }}
